#!/bin/bash
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2013-2014 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
##

set -e

# The path where your MXE directory is located.
MXE=$HOME/mxe-git

# The path where the cross-compiled packages will be installed.
PREFIX=$HOME/sr_mingw

# The path where to download files to and where to build packages.
BUILDDIR=./build

# Edit this to enable/disable/modify parallel compiles.
PARALLEL="-j 2"

# You usually don't need to change anything below this line.

# -----------------------------------------------------------------------------

VER_LIBUSB_WIN32=1.2.6.0
VER_ZADIG=v2.0.1.160

SF_MIRROR=switch.dl.sourceforge.net

WGET="wget --quiet"

# -----------------------------------------------------------------------------

# We need to find tools in the toolchain.
export PATH=$MXE/usr/bin:$PATH

P="$PREFIX/lib/pkgconfig"
P2="$MXE/usr/i686-pc-mingw32/lib/pkgconfig"
C="--host=i686-pc-mingw32 --prefix=$PREFIX"
CM="-DCMAKE_TOOLCHAIN_FILE=$MXE/usr/i686-pc-mingw32/share/cmake/mxe-conf.cmake"
L="--disable-shared --enable-static"

# Remove build directory contents (if any) and create a new build dir.
rm -rf $BUILDDIR
mkdir $BUILDDIR
cd $BUILDDIR

# -----------------------------------------------------------------------------

mkdir -p $PREFIX

# Cross-compiling Python is highly non-trivial, so we avoid it for now.
# The download below is a repackaged tarball of the official Python 3.2.3 MSI
# installer for Windows: http://python.org/ftp/python/3.2.3/python-3.2.3.msi.
# The MSI file has been installed on a Windows box and then c:\Python32\libs
# and c:\Python32\include have been stored in the Python32.tar.gz tarball.
$WGET http://www.sigrok.org/tmp/Python32.tar.gz -O $PREFIX/Python32.tar.gz
tar xzf $PREFIX/Python32.tar.gz -C $PREFIX

# Create a dummy python3.pc file so that pkg-config finds Python 3.
mkdir -p $PREFIX/lib/pkgconfig
cat >$PREFIX/lib/pkgconfig/python3.pc <<EOF 
prefix=$PREFIX
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include
Name: Python
Description: Python library
Version: 3.2
Libs: -L$PREFIX/Python32/libs -lpython32
Cflags: -I$PREFIX/Python32/include
EOF

# The python32.dll and python32.zip files will be shipped in the NSIS
# Windows installers (required for protocol decoding to work).
# The file python32.dll (NOT the same as python3.dll) is copied from an
# installed Python 3.2.3 (see above) from c:\Windows\system32\python32.dll.
# The file python32.zip contains all files from the 'DLLs', 'Lib', and 'libs'
# subdirectories from an installed Python on Windows (c:\python32), i.e. some
# libraries and all Python stdlib modules.
$WGET http://www.sigrok.org/tmp/python32.dll -O $PREFIX/python32.dll
$WGET http://www.sigrok.org/tmp/python32.zip -O $PREFIX/python32.zip

# libusb0.dll (needs to be shipped with frontends)
$WGET -c http://$SF_MIRROR/project/libusb-win32/libusb-win32-releases/$VER_LIBUSB_WIN32/libusb-win32-bin-$VER_LIBUSB_WIN32.zip
unzip -q libusb-win32-bin-$VER_LIBUSB_WIN32.zip
cp -f libusb-win32-bin-$VER_LIBUSB_WIN32/bin/x86/libusb0_x86.dll $PREFIX/libusb0.dll

# Zadig (we ship this with frontends for easy driver switching).
$WGET -c http://$SF_MIRROR/project/libwdi/zadig/zadig_$VER_ZADIG.7z
$WGET -c http://$SF_MIRROR/project/libwdi/zadig/zadig_xp_$VER_ZADIG.7z
7zr e zadig_$VER_ZADIG.7z
7zr e zadig_xp_$VER_ZADIG.7z
cp -f zadig.exe zadig_xp.exe $PREFIX

# libserialport
git clone git://sigrok.org/libserialport
cd libserialport
./autogen.sh
PKG_CONFIG_PATH_i686_pc_mingw32=$P ./configure $C $L
make $PARALLEL V=1
make install
cd ..

# libsigrok
git clone git://sigrok.org/libsigrok
cd libsigrok
patch -p1 < ../../libsigrok_firmwaredir.patch
./autogen.sh
PKG_CONFIG_PATH_i686_pc_mingw32=$P ./configure $C $L
make $PARALLEL V=1
make install
cd ..

# libsigrokdecode
git clone git://sigrok.org/libsigrokdecode
cd libsigrokdecode
./autogen.sh
patch -p1 < ../../srd_decodersdir.patch
PKG_CONFIG_PATH_i686_pc_mingw32=$P ./configure $C $L
make $PARALLEL V=1
make install
cd ..

# sigrok-firmware
git clone git://sigrok.org/sigrok-firmware
cd sigrok-firmware
./autogen.sh
# Nothing gets cross-compiled here, we just need 'make install' basically.
./configure --prefix=$PREFIX
make install
cd ..

# sigrok-firmware-fx2lafw
git clone git://sigrok.org/sigrok-firmware-fx2lafw
cd sigrok-firmware-fx2lafw
./autogen.sh
# We're building the fx2lafw firmware on the host, no need to cross-compile.
./configure --prefix=$PREFIX
make $PARALLEL V=1
make install
cd ..

# sigrok-dumps
git clone git://sigrok.org/sigrok-dumps
cd sigrok-dumps
make install DESTDIR=$PREFIX/share/sigrok-dumps
cd ..

# sigrok-cli
git clone git://sigrok.org/sigrok-cli
cd sigrok-cli
./autogen.sh
PKG_CONFIG_PATH_i686_pc_mingw32=$P:$P2 ./configure $C
make $PARALLEL V=1
make install
makensis -DHOME=$HOME contrib/sigrok-cli_cross.nsi
cd ..

# PulseView
git clone git://sigrok.org/pulseview
cd pulseview
PKG_CONFIG_PATH_i686_pc_mingw32=$P:$P2 cmake $CM -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -DDISABLE_WERROR=y .
make $PARALLEL VERBOSE=1
make install
makensis -DHOME=$HOME contrib/pulseview_cross.nsi
cd ..

