#!/bin/bash
##
## Copyright (C) 2016 Simon Peter
## Copyright (C) 2017 Uwe Hermann <uwe@hermann-uwe.de>
## This file is licensed under the terms of the MIT license.
##

# Bundle PulseView and its dependencies as an AppImage for x86_64 Linux.
# Note: This assumes the full sigrok stack has been installed into $PREFIX.

PREFIX=$HOME/sr

ARCH=x86_64

APP=PulseView
LOWERAPP=${APP,,} 

A="./$APP/$APP.AppDir"
mkdir -p $A/usr/bin $A/usr/lib $A/usr/share
cd ./$APP

wget -q https://github.com/probonopd/AppImages/raw/master/functions.sh -O ./functions.sh
. ./functions.sh

########################################################################
# Get build products from $PREFIX
########################################################################

cd $APP.AppDir/

cp $PREFIX/bin/pulseview usr/bin/
chmod a+x usr/bin/*
cp $PREFIX/lib/lib*.so* usr/lib/
cp -r $PREFIX/share/libsigrokdecode usr/share/
cp -r $PREFIX/share/sigrok-firmware usr/share/

# Reduce binary size
strip usr/bin/*
strip usr/lib/*

########################################################################
# AppRun is the main launcher that gets executed when AppImage is run
########################################################################

get_apprun

########################################################################
# Copy desktop and icon file to AppDir for AppRun to pick them up
########################################################################

wget http://sigrok.org/jenkins/job/pulseview/buildtype=shared,compiler=gcc,platform=native-amd64/ws/contrib/pulseview.desktop
wget -q "http://sigrok.org/gitweb/?p=pulseview.git;a=blob_plain;f=icons/sigrok-logo-notext.png" -O sigrok-logo-notext.png

########################################################################
# Copy in the dependencies that cannot be assumed to be available
# on all target systems
########################################################################

copy_deps

########################################################################
# Delete stuff that should not go into the AppImage
########################################################################

delete_blacklisted
move_lib
mv ./usr/lib/x86_64-linux-gnu/* usr/lib/
rm -r ./usr/lib/x86_64-linux-gnu/

# Remove some incorrectly/unintentionally copied files.
rm -r ./home

########################################################################
# Determine the version of the app; also include needed glibc version
########################################################################

VER1="NIGHTLY"
GLIBC_NEEDED=$(glibc_needed)
VERSION=$VER1.glibc$GLIBC_NEEDED
echo $VERSION

########################################################################
# Patch away absolute paths; it would be nice if they were relative
########################################################################

patch_usr

########################################################################
# AppDir complete
# Now packaging it as an AppImage
########################################################################

cd ..

generate_appimage
