#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2017-2020 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

set -e

# The path where the installed sigrok libraries/binaries are located.
PREFIX=$HOME/sr_macosx

# Build for Apple Silicon (y/n)
APPLE_SILICON=y

if [ "x$1" = "xsigrok-cli" ]; then
	APPNAME="sigrok-cli"
	APPNAME_BINARY="sigrok-cli"
else
	APPNAME="PulseView"
	APPNAME_BINARY="pulseview"
fi

# The path where to download files to and where to build packages.
BUILDDIR=./build_app_$APPNAME_BINARY

if [[ $APPLE_SILICON = y ]]; then
	# Use Qt6 if building for Apple Silicon
  QTVER=qt@6
else
	# We use Qt 5.5 in order to remain compatible with more versions of Mac OS X.
	QTVER=qt@5.5
fi

# Path to Qt5 binaries.
QTBINDIR=`brew list $QTVER | grep bin | head -n 1 | xargs dirname`
QTTRANSLATIONSDIR=`brew --prefix $QTVER`/share/qt/translations

# Path to boost libraries.
BOOSTLIBDIR=`brew list boost | grep libboost_system | grep -v cmake | head -n 1 | xargs dirname`

# Extract path and version of python3 framework from libsigrokdecode using otool
PYTHONFRAMEWORKDIR=$(otool -L $PREFIX/lib/libsigrokdecode.*.dylib | grep python | head -n 1)
PYTHONFRAMEWORKDIR=${PYTHONFRAMEWORKDIR%"/Python.framework"*}
PYTHONFRAMEWORKDIR=$(readlink -f $PYTHONFRAMEWORKDIR)/
PYVER=${PYTHONFRAMEWORKDIR#*@}
PYVER=${PYVER%%"/"*}

# Path to dbus
DBUSLIBDIR=`brew list dbus | grep bin | head -n 1 | xargs dirname`/../lib

# You usually don't need to change anything below this line.

# -----------------------------------------------------------------------------

# Remove build directory contents (if any) and create a new build dir.
rm -rf $BUILDDIR
mkdir $BUILDDIR
cd $BUILDDIR

APPVER="NIGHTLY"

CONTENTSDIR="$APPNAME.app/Contents"
MACOSDIR="$CONTENTSDIR/MacOS"
FRAMEWORKSDIR="$CONTENTSDIR/Frameworks"
SHARE_DIR="$CONTENTSDIR/share"
PYDIR="$FRAMEWORKSDIR/Python.framework/Versions/$PYVER"

mkdir -p $MACOSDIR $FRAMEWORKSDIR $SHARE_DIR

cp $PREFIX/bin/$APPNAME_BINARY $MACOSDIR
# Implementation detail: Shared libraries are handled below.
cp -R $PREFIX/share/libsigrokdecode $SHARE_DIR
rm -rf $SHARE_DIR/libsigrokdecode/decoders/**/__pycache__
rm -rf $SHARE_DIR/libsigrokdecode/decoders/common/**/__pycache__
cp -R $PREFIX/share/sigrok-firmware $SHARE_DIR

if [ "x$APPNAME_BINARY" = "xpulseview" ]; then
	# Manually copy some boost libs that "macdeployqt" won't copy.
	cp $BOOSTLIBDIR/libboost_timer-mt.dylib $FRAMEWORKSDIR
	cp $BOOSTLIBDIR/libboost_chrono-mt.dylib $FRAMEWORKSDIR
	chmod 644 $FRAMEWORKSDIR/*boost*

	# Manually copy translations ("macdeployqt" won't copy them).
	mkdir -p $CONTENTSDIR/translations
	cp $QTTRANSLATIONSDIR/qt_*.qm $CONTENTSDIR/translations
	cp $QTTRANSLATIONSDIR/qtbase_*.qm $CONTENTSDIR/translations

	if [[ $APPLE_SILICON = y ]]; then
		# Copy QtDBus, which should be but is not actually copied by macdeployqt
		cp -R $QTBINDIR/../lib/QtDBus.framework $FRAMEWORKSDIR
		rm -rf $FRAMEWORKSDIR/QtDBus.framework/Headers
		# Copy dbus
		cp $DBUSLIBDIR/*.dylib $FRAMEWORKSDIR
		chmod 644 $FRAMEWORKSDIR/libdbus*.dylib
	fi
fi

$QTBINDIR/macdeployqt $APPNAME.app

# Copy Python framework and fix it up.
cp -R $PYTHONFRAMEWORKDIR $FRAMEWORKSDIR
chmod 644 $PYDIR/lib/libpython*.dylib
rm -rf $PYDIR/Headers
rm -rf $PYDIR/bin
rm -rf $PYDIR/include
rm -rf $PYDIR/share
rm -rf $PYDIR/lib/pkgconfig
rm -rf $PYDIR/lib/python$PYVER/lib2to3
rm -rf $PYDIR/lib/python$PYVER/distutils
rm -rf $PYDIR/lib/python$PYVER/idlelib
rm -rf $PYDIR/lib/python$PYVER/test
rm -rf $PYDIR/lib/python$PYVER/**/test
rm -rf $PYDIR/lib/python$PYVER/tkinter
rm -rf $PYDIR/lib/python$PYVER/turtledemo
rm -rf $PYDIR/lib/python$PYVER/unittest
rm -rf $PYDIR/lib/python$PYVER/__pycache__
rm -rf $PYDIR/lib/python$PYVER/**/__pycache__
rm -rf $PYDIR/lib/python$PYVER/**/**/__pycache__
rm -rf $PYDIR/Resources

PYFRAMEWORKSDIR_SRC=/usr/local/opt/python/Frameworks/Python.framework/Versions/$PYVER/Python
if [[ $APPLE_SILICON = y ]]; then
	PYFRAMEWORKSDIR_SRC=/opt/homebrew/opt/python@$PYVER/Frameworks/Python.framework/Versions/$PYVER/Python
fi
PYFRAMEWORKSDIR_DST=@executable_path/../Frameworks/Python.framework/Versions/$PYVER/Python
install_name_tool -change $PYFRAMEWORKSDIR_SRC $PYFRAMEWORKSDIR_DST $FRAMEWORKSDIR/libsigrokdecode.*.dylib
install_name_tool -change $PYFRAMEWORKSDIR_SRC $PYFRAMEWORKSDIR_DST $PREFIX/lib/libirmp.*.dylib

if [[ $APPLE_SILICON = y ]]; then
	# Sign all binaries recursively
	function sign_all {
		for f in $1/*; do
			file_type_str=$(file -Ih $f)
			mime=${file_type_str#*: }
			if [[ $mime = "inode/directory;"* ]]; then
				sign_all $f
			elif [[ $mime = "application/x-mach-binary;"* ]]; then
				codesign --force -s - $f &> /dev/null || :
			fi
		done
	}
	sign_all $MACOSDIR
	sign_all $FRAMEWORKSDIR
	sign_all $CONTENTSDIR/PlugIns
fi

# Add wrapper (sets PYTHONHOME/SIGROK_FIRMWARE_DIR/SIGROKDECODE_DIR).
mv $MACOSDIR/$APPNAME_BINARY $MACOSDIR/$APPNAME_BINARY.real
cat <<EOT >> $MACOSDIR/$APPNAME_BINARY
#!/bin/sh

DIR="\$(dirname "\$0")"
cd "\$DIR"
export DYLD_LIBRARY_PATH="../Frameworks"
export PYTHONHOME="../Frameworks/Python.framework/Versions/$PYVER"
export SIGROK_FIRMWARE_DIR="../share/sigrok-firmware"
export SIGROKDECODE_DIR="../share/libsigrokdecode/decoders"
exec ./$APPNAME_BINARY.real "\$@"
EOT
chmod 755 $MACOSDIR/$APPNAME_BINARY

cp ../contrib/Info.plist_$APPNAME_BINARY $CONTENTSDIR/Info.plist
cp ../contrib/$APPNAME_BINARY.icns $CONTENTSDIR/Resources

hdiutil create "${APPNAME}-${APPVER}.dmg" -volname "$APPNAME $APPVER" \
	-fs HFS+ -srcfolder "$APPNAME.app"
