#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2017 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

DIR="$(dirname "$0")"
cd "$DIR"
export PYTHONHOME="../Frameworks/Python.framework/Versions/3.6"
export SIGROK_FIRMWARE_DIR="../share/sigrok-firmware"
export SIGROKDECODE_DIR="../share/libsigrokdecode/decoders"
./pulseview.real
